### ISSUE TITLE
Insert Media Option

### ISSUE THREAD

**Issue by mlangone** [anthony-mills/s3-video#10]
Using WP 3.9 the ability to add a single s3 video using the add media option is not working correctly - the insert into page is grayed out and will not add the short code.

**Comment by anthony-mills** [comment]
Thanks for the bug report it seems the code to load in the jQuery library that the media manager uses was broken. I have just changed it to load the library directly from a CDN for the interim and it works again as of 1fd2187

Many Thanks

Anthony
