### ISSUE TITLE
won't insert video code

### ISSUE THREAD

**Issue by jkilgore55** [anthony-mills/s3-video#11]
If in media and select S3 video, although my list of videos shows, and there is a link under "actions" for "Insert Video", when I click it, it does nothing.  Same thing on playlist

Any Ideas?

**Comment by anthony-mills** [comment]
Thanks for the bug report is seems the code to load in the jQuery library that the media manager uses was broken. I have just changed it to load the library directly from a CDN for the interim and it works again as of 1fd2187

Many Thanks

Anthony

**Comment by jkilgore55** [comment]
how do I get the update loaded?

**Comment by anthony-mills** [comment]
Hi mate, 
             To get the updated code us will need to use git to clone the code from the repository here on git hub. This will basically just give you a folder of the code same as if you got it from the Wordpress plugin portal. Then simply copy to the plugin folder on your Wordpress install and you will be good to go.

Cheers

Anthony
